services:
  - type: web
    name: rice-prediction-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn your_project_name.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: your-database-url-here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "rice-prediction-web.onrender.com"
    autoDeploy: true