services:
  - type: web
    name: rice-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rice_prediction.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: rice-prediction.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://rice-prediction.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: rice-prediction-db
          property: connectionString

  - type: pserv
    name: rice-prediction-db
    runtime: postgres
