env: python
envVersion: 3.11.1  # 👈 must be at the top level, not inside 'services'

services:
  - type: web
    name: rice-prediction-app
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn rice_prediction.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://database_n5ff_user:gLhMYElx2nQ9V0NQP3KS3AVb7ESgVSLb@dpg-d3oe3o2li9vc73c2t19g-a/database_n5ff
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "rice-prediction-web.onrender.com"
    autoDeploy: true

  - type: pserv
    name: rice-prediction-db
    runtime: postgres