env: python
envVersion: 3.11.1  # 👈 must be at the top level, not inside 'services'

services:
  - type: web
    name: rice-prediction-app
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn rice_prediction.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://rice_prediction_db_user:tS6zH52KU52h0B7Y2KbvkXs6yZSIWo2f@dpg-d3oiri6mcj7s73f0cu40-a/rice_prediction_db
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "ricepredictiontest.onrender.com"
    autoDeploy: true

  - type: pserv
    name: rice-prediction-db
    runtime: postgres